import { FormEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getProfile, updateProfile } from '../services/profile';
import { useAuthStore } from '../stores/authStore';

export default function ProfilePage(){const {logout,businesses,currentBusinessId,currentBusinessRole,isBusinessOwner}=useAuthStore(); const nav=useNavigate(); const [form,setForm]=useState({name:'',email:'',phone:'',locale:'en',timezone:'Africa/Accra'}); const [msg,setMsg]=useState(''); const [saving,setSaving]=useState(false); useEffect(()=>{getProfile().then(u=>setForm({name:u.name,email:u.email,phone:u.phone||'',locale:u.locale||'en',timezone:u.timezone||'Africa/Accra'}))},[]); const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await updateProfile(form);setMsg('Profile updated successfully.')}catch(err:any){setMsg(err?.response?.data?.message||'Could not update profile.')}finally{setSaving(false)}}; const signout=async()=>{await logout();nav('/login')}; const currentBusiness=businesses.find(b=>b.id===currentBusinessId)||businesses[0];
const roleLabel=isBusinessOwner||currentBusinessRole==='owner'
  ?'Owner'
  :currentBusinessRole==='inventory_officer'
    ?'Inventory Officer'
    :currentBusinessRole
      ?currentBusinessRole.charAt(0).toUpperCase()+currentBusinessRole.slice(1)
      :'Staff';

return <div className="mx-auto max-w-xl space-y-4"><h1 className="text-xl font-bold">Profile</h1><div className="rounded-xl bg-white p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-3"><div><div className="text-xs font-medium uppercase tracking-wide text-slate-500">Role</div><div className="mt-1 font-semibold text-slate-900">{roleLabel}</div></div><div><div className="text-xs font-medium uppercase tracking-wide text-slate-500">Business</div><div className="mt-1 font-semibold text-slate-900">{currentBusiness?.name||'—'}</div></div><div><div className="text-xs font-medium uppercase tracking-wide text-slate-500">Branch</div><div className="mt-1 font-semibold text-slate-900">{currentBusiness?.branch_id?'Assigned branch':'Head Office'}</div></div></div></div>{msg&&<div className="rounded-lg bg-slate-100 px-4 py-3 text-sm">{msg}</div>}<form onSubmit={submit} className="space-y-3 rounded-xl bg-white p-5 shadow-sm"><input required className="w-full rounded-lg border px-3 py-2.5" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" className="w-full rounded-lg border px-3 py-2.5" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="w-full rounded-lg border px-3 py-2.5" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="w-full rounded-lg border px-3 py-2.5" placeholder="Timezone" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/><button disabled={saving} className="w-full rounded-lg bg-teal-700 py-2.5 font-semibold text-white">{saving?'Saving…':'Save profile'}</button></form><button onClick={signout} className="w-full rounded-lg border border-red-200 bg-red-50 py-2.5 font-semibold text-red-700">Sign out</button></div>}
